### ISSUE TITLE
Type not found : openfl.utils.JNI

### ISSUE THREAD

**Issue by wilfryed** [HaxeExtension/extension-share#25]
Hi!

Can't compile my project while using the extension-share, got that error:

`C:/HaxeToolkit/haxe/lib/extension-share/2,4,3/extension/share/Share.hx:18: characters 75-81 : Type not found : openfl.utils.JNI
`
flixel 4.5.1
hxcpp 4.0.4
lime 7.1.1
openfl 8.6.4

**Comment by jgranick** [comment]
Does it work if you use the GIT version of the library?

**Comment by wilfryed** [comment]
Nope!

But just to be sure if I tried well, I downloaded the GIT version, put Share.hx and BBShareDialog.hx in my project, and replace the first lines concerning packaging with package;

Just tell me if I'm right or not.

**Comment by jgranick** [comment]
Okay, try again: https://github.com/HaxeExtension/extension-share/commit/06a08c753a3278da4a1d8b5c1818360ccd08ae05

**Comment by wilfryed** [comment]
Work perfectly!

Thanks a lot for your time.
